### ISSUE TITLE
Include black and white color ? 

### ISSUE THREAD

**Issue by jaumard** [99designs/colorific#15]
Hi,

It's possible to include white and black colors ? Or can you add an option to add them ?

Thanks
Jim

**Comment by deronsizemore** [comment]
Hello. Was hoping someone was still monitoring this.

I'm attempting to use this with a django application have it working except that it seems to still be excluding black colors even though I've passed min_saturation=0. Here's my code:

    extracted_palette = palette.extract_colors(image, max_colors=10, min_saturation=0)

Can you help me out here with including black? Why isn't this working?

Thanks
